### ISSUE TITLE
Handling different User classes.

### ISSUE THREAD

**Issue by holden** [intercom/intercom-rails#100]
On a current project we have 3 different User models (2 that are important for Intercom).  One for Venues and one for QuizMasters.  Both respond to the current_user method so at first glance it seems to work, but I'm wondering if there will be an issue since the `user_id` will overlap since they are different models and the ids would not be unique between models.

Eg I'm sure there is a 'user' in both models with the id of 42.

What can I do for make intercom aware of this?  Or do I need to?

Thanks!

**Comment by eoin** [comment]
Prefixing the user id with a class identifier, e.g. `venue_1234` will do the trick.
