### ISSUE TITLE
Using other method as unique id for users

### ISSUE THREAD

**Issue by pietere** [intercom/intercom-rails#106]
Hello,

I'd like to use another method than `current_user.id` to send to intercom.

I have defined a method `intercom_id` which I would like to be called instead of `.id`

How can this be done?

This is what I tried

```
  config.user.current = Proc.new { 
    _intercom_id = current_user.intercom_id
    current_user.define_singleton_method(:id) { _intercom_id }
    current_user
  }
```

in combination with 

```
config.user.custom_data = {
      :id => Proc.new { |current_user| current_user.intercom_id },
      ...
```

but so far, no luck. I keep on getting the result of user.id in intercom.

**Comment by jguitar** [comment]
Hi!

I'm finding something similar, is it possible?

**Comment by pietere** [comment]
I think I solved it with defining both ID and USER_ID

      :id => Proc.new { |current_user| current_user.intercom_id },
      :user_id => Proc.new { |current_user| current_user.intercom_id },

however, not sure if it's a clean solution

**Comment by jguitar** [comment]
thanks @pietere I'm going to try it.
At least, it's a solution ;)

**Comment by bobjflong** [comment]
Hey, to use a custom `id`, I would suggest manually injecting the snippet: https://github.com/intercom/intercom-rails#manually-inserting-the-intercom-javascript

Or: perhaps define a custom object with separate fields for the current user:

```ruby
class IntercomUser
# ...
end

config.user.current = Proc.new do
  IntercomUser.from_authenticated_user(current_user)
end
```

**Comment by olliebennett** [comment]
Hi. I am also experiencing this, as we use [HashIDs](hashids.org) as our User IDs. @bobjflong it would be awesome if you could provide a more complete example here.

It might also be a consideration to use `.to_param` rather than `.id`. This is what is used (for example) when generating resource URLs (using the helpers), so is expected to be unique.
