### ISSUE TITLE
Cache company name

### ISSUE THREAD

**Issue by axelson** [intercom/intercom-rails#107]
I'd like to be able to cache the company name of the current user without loading my company model. However I am not sure how to do that since it appears that the company name is determined by running `company.name` after loading the company from `config.company.current = Proc.new { current_user.company }`.

I'd rather not cache the entire company model because the cache invalidation could be tricky, but caching the name (especially if it was just for intercom) would be fine. Am I missing something simple?

**Comment by bobjflong** [comment]
Hey @axelson 

What company attributes do you track in Intercom? Only name? Would something like this work for you?

```ruby
config.company.current = Proc.new do
  cached_name = cached_company_name_for_user #hit your cache
  OpenStruct.new( #Dummy object for the cached name
    name: cached_name
  )
end
```
