### ISSUE TITLE
skip_after_filter :intercom_rails_auto_include does not work with turbolinks

### ISSUE THREAD

**Issue by armilam** [intercom/intercom-rails#108]
In our app, we are using turbolinks and intercom-rails. We do not want the Intercom interface to show up for views under LessonsController, so we include the line `skip_after_filter :intercom_rails_auto_include` in that controller.

When we visit a page in LessonsController directly, the Intercom include is not served to the client (as expected).

However, if the client starts in a view under DashboardController (which does include Intercom), then clicks a link to a view in LessonsController, the Intercom interface is still shown because turbolinks does not remove the Intercom include.

**Comment by armilam** [comment]
My current workaround is to add the class `.hide-intercom` to the body of those pages and add the following to the CSS:

    .hide-intercom .intercom-container {
      display: none;
    }

**Comment by eoin** [comment]
Hi there, sorry about the delay in responding to this. I'd recommend using our client-side API in this case to close the messenger on these pages.

e.g. the following will close the messenger:

```
Intercom('shutdown')
```

There's more information here http://docs.intercom.io/install-on-your-web-product/intercom-javascript-api.
