### ISSUE TITLE
Changing config on a per-pageload basis

### ISSUE THREAD

**Issue by aguynamedben** [intercom/intercom-rails#109]
Hi, I run a multitenant app with 2 tenants. I want to configure Intercom to send data to 2 Intercom app_ids based on the subdomain of the current page load. Current, config/initializers/intercom.rb doesn't allow me to do this because config.app_id, config.api_secret, and config.api_key are set upon server startup, not upon page load. I was looking at https://github.com/intercom/intercom-rails/blob/master/lib/intercom-rails/config.rb#L22 to figure out if I could pass a Proc or a block to IntercomRails, but it doesn't look like I can.

Is there a way to set my Intercom credentials dynamically (i.e. similar to how current user gets set with a Proc), without just abandoning all the Rail-y config this app provides and going straight Javascript/helper?

Thanks.

-Ben

**Comment by aguynamedben** [comment]
Nevermind, I see in the README's 

`You can also override IntercomRails::Config options such as your api_secret, or widget configuration with a second hash (in the helper script tag)`

Sorry for asking before RTFM. Nice work on this gem.

**Comment by lorcan** [comment]
Thanks Ben, let us know if you have any problems.
