### ISSUE TITLE
Only show messenger inbox to certain types of users

### ISSUE THREAD

**Issue by weavermedia** [intercom/intercom-rails#110]
I have several types of user accessing my app: `Teacher`, `Student`, `Parent`, etc. I want to observe all types but only show the messenger inbox to `Teacher` types.

Is there a way to achieve this without having to code a custom `intercom_script_tag`?

I hoped there might be a config option for it, something like:

`config.show_inbox = Proc.new { |user| user.type == 'Teacher' ? true : false }`

I tried passing a similar Proc into `config.inbox.style` to switch to custom style (ie hide the icon) but it didn't work.

**Comment by krismartin** [comment]
My workaround is to allow `config.inbox.style` to have nil value. When inbox.style is set to nil, no widget options will be attached to the intercomSettings script. This is already supported in the `ScriptTag` class, so no other changes are required.

And then in my ApplicationController, I created this before_filter to set the inbox.style:

```
before_filter :set_intercom_widget_inbox_style

def set_intercom_widget_inbox_style
  if current_user.is_a?(Teacher)
    IntercomRails.config.inbox.style = :default
  else
    IntercomRails.config.inbox.style = nil
  end
end
```

Here's my fork:
https://github.com/krismartin/intercom-rails/commit/accd9afb5f998467f2911f65d0ec57d44a6aeb16

**Note:** You also need to disable the in-app messenger option in your Intercom settings as described here:
http://docs.intercom.io/configuring-Intercom/in-app-messenger#can-i-make-the-in-app-messenger-only-available-to-selected-users

What do you guys think? I'll create a pull request and update the test spec if you guys think this is acceptable.

**Comment by weavermedia** [comment]
This fork is working well for me, thanks.

There's probably a better way to implement this though. Setting `inbox.style` to nil doesn't feel right - seems like it should be `:none`. Or maybe setting `inbox` to `:false` might be more semantic?

**Comment by krismartin** [comment]
@weavermedia good idea! I like `:false`.

**Comment by choran** [comment]
Ok, looks like the workaround worked. 
At the moment I dont think we have a plan to include this in the plugin.
