### ISSUE TITLE
Import rake task doesn't work when secure mode is enabled.

### ISSUE THREAD

**Issue by gspiers** [intercom/intercom-rails#113]
Hello. We had a problem importing users using the rake task. This seems to be a problem when secure mode is on. It worked perfectly before we enabled that on our Intercom account.

When secure mode is enabled on the account the rake task fails with:

````
IntercomRails::IntercomAPIError: The Intercom API request failed with the code: 500, after 3 attempts.
````

We had a suspicion that the import task needed the user_hash to be calculated and sent with the request. See [this commit](https://github.com/shinydevelopment/intercom-rails/commit/d10a0c2e1321e0707691997b1448f7b6d52a4877) on our fork.

This worked, but I didn't do a pull request as I suspect the correct fix is to allow import without the user_hash as the user_hash is for protecting against forgery in the browser. Where as the import script is run on the server.

If you disagree I'm happy to clean up our fork of course. The code to calculate the user_hash shouldn't be duplicated and I'd be happy to clean that up.

Thanks,

Greg

**Comment by dgilperez** [comment]
Got hit by this as well. Any temporal workaround we can use in production? Thanks!

**Comment by gspiers** [comment]
@dgilperez Sorry for the late reply. This was our temporary work around https://github.com/shinydevelopment/intercom-rails/commit/d10a0c2e1321e0707691997b1448f7b6d52a4877

**Comment by eugeneius** [comment]
Hey Greg - thanks for writing this up, and sorry it took us so long to get back to you.

I've checked the bulk create API endpoint used by the import rake task, and it doesn't look for secure mode or attempt to compare the user_hash value. I imported some users to an app with secure mode enabled as a test, and it worked fine.

Are you performing regular imports using this task? If so, could you try one without sending the user_hash? If it still fails, I can look into what's happening on our side.

**Comment by gspiers** [comment]
@eugeneius We used it as a one time import originally. On our staging server I just tried the rake task again and it worked without errors.

I can't remember if originally this rake task worked on our staging environment (the test Intercom environment) and failed on production. Unfortunately I can't run that rake task again on our real Intercom account. But I suspect if it's working for the test environment it is probably working for the real environment as well.

Thanks for your help, just let me know if you want to try some other testing. Maybe @dgilperez can confirm if it's still a problem when importing in production?

**Comment by eugeneius** [comment]
I've looked over our historical metrics for the bulk import endpoint. The only errors we've seen in the last few months have been transient infrastructure-level errors, such as a database write being rejected. Importing a large batch of users is a heavy operation, so this can happen - it's why the task [retries each batch up to three times](https://github.com/intercom/intercom-rails/blob/v0.2.28/lib/intercom-rails/import.rb#L136). It's possible you were just unlucky and had three failed requests in a row, and by the time you tried again with your user_hash patch applied the problem had resolved itself.

@dgilperez if you're still having trouble importing your users, could you email team@intercom.io with the details so we can look into it? It's unlikely to be related to secure mode, but without more information I can't do much to help.
