### ISSUE TITLE
Add Companies in Initializer

### ISSUE THREAD

**Issue by GolfyMcG** [intercom/intercom-rails#118]
Hey there,

Gotta start by saying I love Intercom and that it's got an incredible developer onboarding process. Unfortunately, I've hit a snag with getting companies set up.

To start, we use devise so our intercom user config works with the default `current_user` and required no work. We also have a `Company` model and `User`'s have one company. Ie. If you were to execute `current_user.company` in the controller, you would get an instance of of the class `Company`.

Here's where the trouble arises. I have attempted the two suggested solutions in the Intercom initializer for adding a company to Intercom.

First, I uncommented:

```ruby
# config/initializers/intercom.rb

config.user.company_association = Proc.new { |user| [user.company] }
```

I presumed this would execute something like this at some point:

```ruby
IntercomRails.config.user.company_association.call(current_user)
```

And it would return `current_user`'s company in an array. When I do this from the console, it does return just that. It does not do this in the app though. I've also attempted to replace the `Proc` with just returning any instance of `Company` by doing:

```ruby
# config/initializers/intercom.rb

config.user.company_association = Proc.new { |user| [Company.first] }
```

This did not work either, so I moved onto the other option of `current_company` by uncommenting:

```ruby
# config/initializers/intercom.rb

config.company.current = Proc.new { current_company }
```

I also defined the following helper:
```ruby
# app/helpers/application_helper.rb

module ApplicationHelper
  ...
  def current_company
    if current_user
      current_user.company
    end
  end
  ...
end
```

This didn't work though so I checked if I can just provide a random `Company` object and just return something. I then update the initializer to:

```ruby
# config/initializers/intercom.rb

config.company.current = Proc.new { Company.first }
```

This did work and I managed to get a company on Intercom.io. From here, I've tried to work together some sort of solution but I have not been able dynamically produce a company for my users. As I mentioned before, I expected the following to be executed somewhere:

```ruby
IntercomRails.config.user.company_association.call(current_user)
```

I started to look through the source code here and in https://github.com/intercom/intercom-ruby and the I believe the `Proc` is called [here](https://github.com/intercom/intercom-rails/blob/e54efe1793dbd9f0af58c2588e399d50cf6d9ca3/lib/intercom-rails/proxy/company.rb#L16):

```ruby
# intercom-rails/lib/intercom-rails/proxy/company.rb

def self.companies_for_user(user)
  return unless config(:user).company_association.present?
  companies = config(:user).company_association.call(user.user)
  return unless companies.kind_of?(Array)

  companies.map { |company| new(company) }.select { |company_proxy| company_proxy.valid? }
end
```

Though, I think this is only called in the importing script, I don't understand what `user.user` does. Any help would be appreciated. Please let me know if I can provide any further information.

**Comment by eoin** [comment]
Thanks for pointing this out. We're going to take a look and will get back to you ASAP.

**Comment by GolfyMcG** [comment]
@eoin - thank you!

**Comment by GolfyMcG** [comment]
I'm continuing to look into this and I'm perplexed by your specs for companies.

Is [this](https://github.com/intercom/intercom-rails/blob/97803b97d8a7b2e28ca1dd150f99722c4030279f/spec/proxy/company_spec.rb#L33) line referring to several companies as apps? Are those the same `apps` as are referenced to in the config file on [this](https://github.com/intercom/intercom-rails/blob/cd08f3e946e2957c3966737662a098fc5c3aaea2/lib/rails/generators/intercom/config/intercom.rb.erb#L90) line?

If that is true, wouldn't a more semantic naming be:
```
config.company.custom_data = {
  :number_of_messages => Proc.new { |company| company.messages.count },
  :is_interesting => :is_interesting?
}
```

**Comment by GolfyMcG** [comment]
I'm attempting to display this in the view:
```
<%= IntercomRails.config.company.current.call %>
```

This throws an error saying
> undefined local variable or method `current_company' for main:Object

While this returns the company successfully:
```
<%= current_company %>
```

To me, says that `current_company` is defined but is not accessible to the config files. My rather heavy handed solution was to add `include ApplicationHelper` at to the top of the initializer. This resulted in slightly different error:
> undefined local variable or method `current_user' for main:Object

As in it couldn't determine the `current_user` from `Devise. Do you have a suggested implementation of `current_company` that doesn't involve a helper?

**Comment by GolfyMcG** [comment]
I have also tried testing this in the view:
```
<%= IntercomRails.config.user.company_association.call(current_user) %>
```
And it returns the correct company.

**Comment by GolfyMcG** [comment]
So it seems to me that the different possible solutions each have a slightly different issues. In the first case:
```
config.user.company_association = Proc.new { |user| [user.company] }
```
The above method is defined correctly but never seems to be called. I've been able to call it manually but nothing is sent to Intercom.

In the second case:
```
config.company.current = Proc.new { current_company }
```
The above method is not defined (or more specifically `IntercomRails` fails to recognize the `current_company` and `current_user` methods) but the `Proc` itself is definitely called when syncing with Intercom. I know this because when I replace `current_company` with `Company.first`, Intercom behaves as expected and the company shows up in the web UI.

**Comment by GolfyMcG** [comment]
Good news! As it turns out, `current_user` is accessible from within `IntercomRails`. Unless I've mistaken the appropriate implementation is:

```
config.company.current = Proc.new { current_user.company }
```

I would recommend clearing that up in the config generator. If you'd like help doing so, I can rewrite it in a way that is clearer to me and submit a PR.

**Comment by ocfnash** [comment]
Hi Alex,

thanks so much for documenting your progress so clearly here. I am delighted you managed to get things working despite some less than ideal semantics on our part.

Regarding a possible PR, while that is a great idea, I think there is no need. We already have a plan to give this gem some love in the not-too-distant future and we will fix the confusing issues you faced then.

Don't hesitate to get in touch if you have any other problems.

**Comment by dcorking** [comment]
:+1: I have stumbled into the same confusion and it cost me and your support engineer a huge amount of time - please document this in the README and in the generator template.

**Comment by marckohlbrugge** [comment]
👍 I'm running into the same issue. Using @GolfyMcG's solution doesn't seem to work for me.

**Comment by choran** [comment]
ok, cool. We have updated the docs in relation to this.
Thanks for raising this issue.
