### ISSUE TITLE
Importing users from different tenants  

### ISSUE THREAD

**Issue by mkosuri** [intercom/intercom-rails#120]
Importing user from different tenants not working i used the below code ...

namespace :users_importing_to_intercome do
  desc "Importing users to Intercom"
  task creation_of_user: :environment do
    Tenant.all.pluck(:name).each do |tenant_name|
      Apartment::Tenant.switch(tenant_name)
      begin
        IntercomRails::Import.run(:status_enabled => true)
      rescue IntercomRails::ImportError => e
        puts e.message
      end
    end
  end
end

**Comment by choran** [comment]
Looks like a duplicate of https://github.com/intercom/intercom-rails/issues/119
So closing this. If it is still and issue then please feel free to re-open it and provide any error msgs you are seeing.
