### ISSUE TITLE
Getting 500 from import rake task 

### ISSUE THREAD

**Issue by rossgeesman** [intercom/intercom-rails#121]
Found user class: User
Intercom API key found
Sending users in batches of 100:
rake aborted!
IntercomRails::IntercomAPIError: The Intercom API request failed with the code: 500, after 3 attempts.

Any ideas on how to fix this?

**Comment by eoin** [comment]
Hi @rossgeesman, would you mind getting in touch with us at team@intercom.io with your app id and we'll take a look?
