### ISSUE TITLE
What would cause the script to not auto inject?

### ISSUE THREAD

**Issue by noctivityinc** [intercom/intercom-rails#127]
The script does not appear to auto inject.  If I add 

    <%= intercom_script_tag %>

Then it appears to work but we're unclear if we now need to specify all the custom data values if we auto inject.  It's not apparent in the docs.

Why would auto inject not work, how can we troubleshoot it and do we need to use js to define standard and custom data if it fails?

**Comment by constantm** [comment]
@noctivityinc Did you manage to figure this out? We just realised Intercom isn't being included on our site any longer, and I'm trying to figure out since when, and why.

**Comment by noctivityinc** [comment]
No we didn’t.  We ended up switching to the pure javascript implementation.



Joshua Lippiner  
.:t 704.323.5661
.:e jlippiner@noctivity.com (mailto:jlippiner@noctivity.com)

**Comment by choran** [comment]
@noctivityinc just checking if you are still having issues with the auto-inject feature? If you are can you please mail us at team@intercom.io with any examples of how you were using this? We can follow up with any docs questions you may have in this channel also.
