### ISSUE TITLE
Setting Location Data

### ISSUE THREAD

**Issue by hamitturkukaya** [intercom/intercom-rails#128]
Hi can i set location data in config file? I couldnt find attributes in intercom-rails/config.rb and i generate location hash as a custom data object. 

Now my intercom javascript object like this.

```json
{
  "app_id": 111,
  "email": "aaa@gmail.com",
  "created_at": 1433251402,
  "user_id": 1,
  "name": "JOHN DOE",
  "first_name": "JOHN",
  "last_name": "DOE",
  "company": {
    "id": 1018,
    "name": "xx",
    "created_at": 1433251504,
    "plan": 1,
    "monthly_spend": 1,
    "sector": ""
  },
  "location_data": {
    "type": "location_data",
    "postal_code": 20070,
    "city_name": "Denizli"
  }
}
```

It is like https://doc.intercom.io/api/#user-model json but city_name doesn't appear on my panel.

How can i set this attribute without using intercom-ruby gem.

**Comment by choran** [comment]
Hi,
Unfortunately, at present it is not possible to update the location data via the [API](https://developers.intercom.io/reference#user-model). The only way you can currently update a Users' location is by sending the [last_seen_ip](https://developers.intercom.io/reference#user-model).  If you would like further clarification on this them please reach out to us via team@intercom.io. Alternatively, we are trialing a new [repo chat](https://gitter.im/intercom/intercom-rails) where the Intercom developer community can get together to discuss issues. This might be a good place to discuss queries such as this.

**Comment by ctessmer** [comment]
@choran You said "unfortunately." Is it safe to assume then, that Intercom will one day let us update our customer's location via the API?

As I look at my users in Intercom, I'm noticing many of their locations are wrong. (They have a physical business address which I know from their profile). This is a case where a human is actually more accurate than a computer. Why not let us update their record? What is the rationale by keeping this location property private/locked down?
