### ISSUE TITLE
Intercom-rails fails silently on intercom.rb error

### ISSUE THREAD

**Issue by constantm** [intercom/intercom-rails#130]
I've been trying to figure out why Intercom is no longer included on our site. Turns out it was due to a change in our database schema. `config.user.exclude_if` referred to a column in the database which no longer existed. I would expect any issues arising from Intercom-rails to be reported somewhere, instead of failing silently?

**Comment by choran** [comment]
Hi, 
Unfortunately I cannot think of an easy way to catch this. If the value `config.user.exclude_if`is true then I cant think of some way this can be reported other then general logging? 
We are trialing a [repo based forum](https://gitter.im/intercom/intercom-rails) for Intercom-Rails which you may find useful to discuss issues like this with other developers. They may have some interesting ideas based on their experiences.

**Comment by constantm** [comment]
Thanks, this was sorted out a loooooong time ago.
