### ISSUE TITLE
Overwriting the app_id

### ISSUE THREAD

**Issue by jerome** [intercom/intercom-rails#132]
Hello

Passing a dynamic app_id in the intercom_script_tag makes the helper ignoring all IntercomRails config data.

We do not set the app_id in the intercom.rb settings file since the tag is dynamically loaded with ajax through cached pages and a rails app serving multiple websites and using multiple intercom apps.

Thanks !

**Comment by bobjflong** [comment]
Hi @jerome could you explain this bug a little more? The `intercom_script_tag` functions ignores the global config?

**Comment by jerome** [comment]
In the contrary: you cannot pass an app_id in the intercom_script_tag. It is ignored. Only the global config prevails.

**Comment by jerome** [comment]
up ?
