### ISSUE TITLE
Bulk updating users

### ISSUE THREAD

**Issue by OwenBannister** [intercom/intercom-rails#136]
We have an app that we need to bulk update all users in Intercom after certain events. Is IntercomRails::Import.run(:status_enabled => true) the best way to do this? Or is there another call that I'm missing?

**Comment by topherfangio** [comment]
In a similar vein, is it safe to run `rake intercom:import` multiple times?

In my case, we're wanting to track some new DB fields in Intercom and retroactively update old users without waiting for them to login.

@OwenBannister Did you wind up doing any testing of the `IntercomRails::Import.run` method you listed above? Would love to know if you had any side-effects.

**Comment by jeremyhaile** [comment]
I'd also like to know if there's a way to bulk update users and companies that is safe to rerun on a regular basis. For example a weekly or nightly job.

**Comment by choran** [comment]
The best way to do this is probably via the Ruby gem itself (intercom-ruby) since this has specific examples relating to bulk actions such as this.
