### ISSUE TITLE
User information leaked during Devise password reset

### ISSUE THREAD

**Issue by abraham-chan** [intercom/intercom-rails#138]
When intercom-rails is used with Devise, submitting a "forgot my password" form results in a 302 redirect. Inspecting the raw response using a network tool like fiddler shows that Intercom is included and reveals user information.

One possible solution is to add a default blacklist of controllers into the initializer file e.g.
`config.blacklisted_controllers = ["Devise::PasswordsController"]`

A manual workaround is to add `skip_after_filter :intercom_rails_auto_include` to your passwords controller

Steps to reproduce:
 1. A default install of devise and intercom-rails (one available here: https://github.com/abraham-chan/rails-devise)
 2. Create a user
 3. Go to `/users/password/new`
 4. Enter a valid user email and submit the form
 5. The raw response of the POST will look something like this:

```
HTTP/1.1 302 Found
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: http://10.0.1.2:3000/users/sign_in
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 3acadaa7-006f-4976-97dd-a0b3748fb832
X-Runtime: 0.522203
Server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
Date: Thu, 01 Oct 2015 01:33:32 GMT
Content-Length: 841
Connection: Keep-Alive
Set-Cookie: request_method=POST; path=/
Set-Cookie: _rails-devise_session=b202aThWZ2VsTjlXRy9aZ0FjRE1NSHVDYkdYcG1RMHNqK0d4cTF4b3pkMk9idFgwOENLQzF5ajVTcFhFVWpvYWk4WG9ZaFRZTWUzdGNtUmZBd0RVekVmTnQzbWlMU0RqZXFiSkJvSTVNMHV3UWk5WGxXUU1Cay9IYUp2YXVjN01xeUVjZWlGakhEeGk0c1RnYXlTSVV0VXVoYzk3QTZRd1Y5V2gzbUhEYm5WbE5yZE1UWUpoVndGL2UwaDdkVTZvQlk1QXdiUmUvZ1JRMElZUmloTFpLdGhuQi8xYmhYOTJiL3lFREhkY0JNeGlpcDJRaVd6UU5MejhpS2oxazlkVmcxUGg4UERyZC8rbHVVSVo2WWFwNytDZlI2N2VsdUFtWmNEaEZYMGcxTDdWbHRIRXlVUUp5VUlzRHFORHA2NlVQTW1nenM4NGdWYXZMOGxJQTFJTm1nPT0tLVBRMlJtZnQ5cmdQTVFjM2ViZzhuMmc9PQ%3D%3D--e5ccb707c944965e96c93174d6e2910e348292fe; path=/; HttpOnly
 
<html><body>You are being <a href="http://10.0.1.2:3000/users/sign_in">redirected</a>.<script id="IntercomSettingsScriptTag">
  window.intercomSettings = {"email":"santa@northpole.com","name":"Santa Clause","created_at":1443662565,"user_id":1,"app_id":"abcd1234"};
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/abcd1234';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()</script>
</body></html>
```

**Comment by eoin** [comment]
Thanks for this @abraham-chan. We're currently looking at this.

**Comment by BastienL** [comment]
I just wanted to point out that if for any reason you override the `Devise::PasswordsController`, then the fix won't work as the `controller.class.name` will be the name of the overriding controller.

Do you think it would make sense to allow extending the `BLACKLISTED_CONTROLLER_NAMES` array?

Meanwhile, a `skip_after_action :intercom_rails_auto_include, only: :create` callback in the overriding controller makes the job.
