### ISSUE TITLE
Acts as Paranoid

### ISSUE THREAD

**Issue by rsiddle** [intercom/intercom-rails#141]
When using a soft delete function such as the https://github.com/ActsAsParanoid/acts_as_paranoid gem, it doesn't delete the user from Intercom because it's only setting a datetime stamp and provides some scopes.

There needs to be a way of deleting these users.

**Comment by eoin** [comment]
If you'd like to delete users in Intercom manually, I'd recommend using our API client directly.

https://github.com/intercom/intercom-ruby
