### ISSUE TITLE
Intercom API Error: The Intercom API request failed with the code: 401, after 3 attempts.

### ISSUE THREAD

**Issue by jbernardo95** [intercom/intercom-rails#144]
Hi, 

When trying to run `rake intercom:import` I get the following result:

```bash
Intercom API Error: The Intercom API request failed with the code: 401, after 3 attempts.
```

Any guess why this is happening ?

**Comment by bobjflong** [comment]
`401` would imply that your API keys are incorrect. Would you mind getting in touch through the Intercom widget at `https://app.intercom.io` as it will be easier to take a look?
