### ISSUE TITLE
Make user attributes configurable

### ISSUE THREAD

**Issue by thomassnielsen** [intercom/intercom-rails#145]
Currently, `intercom-rails` assumes that the current user object has at least an `id`, `name`, `email` and `created_at`. In our case, this provided to be quite a hassle, since `name` is a method that that takes an argument, while the name is `full_name` (for legacy reasons). It would be nice to be able to configure these, or at least to add a section to the readme about how to work around this in config if possible.

**Comment by bobjflong** [comment]
Hi @thomassnielsen - to confirm a workaround, would something like this work for you?

```ruby
config.user.current = Proc.new do
  your_user = find_your_user
  OpenStruct.new(
    name: your_user.full_name,
    email: your_user.email, #etc
  )
end
```

**Comment by thomassnielsen** [comment]
That seems like a workable solution. Would that work as of now, or are there any changes required?

**Comment by bobjflong** [comment]
I'm pretty sure that this should work right now. It's documented as an option when troubleshooting: https://github.com/intercom/intercom-rails#troubleshooting

**Comment by bobjflong** [comment]
Please re-open if this doesn't work out!
