### ISSUE TITLE
WebSocket handshake: Unexpected response code: 405

### ISSUE THREAD

**Issue by alokpant** [intercom/intercom-rails#152]
I am not sure if this is the place to post the error but while running SEO manager it identified these errors:

WebSocket connection to 'wss://nexus-websocket-a.intercom.io/pubsub/1--bqY9dM8UYx8H6d8ZWPaMLPfXCpfaCMgSj-gGEcj573o4S0o?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.6-javascript&X-Atmosphere-Transport=websocket&X-atmo-protocol=true&X-Nexus-Version=0.0.66' failed: Error during WebSocket handshake: Unexpected response code: 405
Source file: https://js.intercomcdn.com/intercom.4c678929.js at line: 6, column: 0

WebSocket connection to 'wss://nexus-websocket-b.intercom.io/pubsub/1--bqY9dM8UYx8H6d8ZWPaMLPfXCpfaCMgSj-gGEcj573o4S0o?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.6-javascript&X-Atmosphere-Transport=websocket&X-atmo-protocol=true&X-Nexus-Version=0.0.66' failed: Error during WebSocket handshake: Unexpected response code: 405
Source file: https://js.intercomcdn.com/intercom.4c678929.js at line: 6, column: 0

**Comment by choran** [comment]
HI  alokpant ,
I was just wondering if you were still encountering this error?
If you are then please re-open this and let us know if you are having any other issues with your Intercom Rails configuration. Were you able to install and set it up correctly or were there issues? Alternatively, we are trialing a Developer Forum **[here](https://gitter.im/intercom/intercom-rails)** where you can discuss issues like this other other people using Intercom Rails. Alternatively, please feel free to re-open the issue if it is still re-occurring.
Cheers
Cathal
