### ISSUE TITLE
Intercom doesn't get loaded locally in Firefox

### ISSUE THREAD

**Issue by sharq1** [intercom/intercom-rails#155]
It works fine in Chrome, but in Firefox the script just doesn't get loaded.

This is the output from console (I also tried including the script in html, but with the same effect):

![screenshot_2](https://cloud.githubusercontent.com/assets/1241239/11419355/ec301838-9426-11e5-8b0b-489d5f13becd.png)

Yet after pasting content of the script into console it starts to work:

![screenshot_3](https://cloud.githubusercontent.com/assets/1241239/11419387/237c0bb2-9427-11e5-9532-a19a16557771.png)

Some of our users have problems with chat not working at all - I wonder whether this might be the reason.

**Comment by choran** [comment]
Hi sharq1,
I was unable to re-create this issue. Did you have trouble installing the Intercom-Rails Plugin? i.e. did this problem occur after you installed it or did this occur intermittently? If it is still an issue then you should reach out to our support team (team@intercom.io) with some more info on the steps that you took to set this up and any other errors or problems you are seeing. Alternatively, we are trialing a Developer Forum for issues like this where you might be able to discuss them with other developers: https://gitter.im/intercom/intercom-rails. But please feel free to re-open this if you are still having issues.
Cheers
Cathal
