### ISSUE TITLE
Allow custom data to be a Proc which returns a hash

### ISSUE THREAD

**Issue by graemeboyd** [intercom/intercom-rails#156]
I'd like to be able to define user and company custom data as a Proc which at runtime is called with the user or company.  The Proc would return a hash which would be set as the custom data and sent to Intercom.  This would allow us to share the custom data we're sending to Intercom between intercom-ruby and intercom-rails.  Presently we have to duplicate the custom data definition which means they get out of sync.

```ruby
config.user.custom_data = Proc.new { |user| SomeObject.user_custom_attributes(user) }
```

**Comment by choran** [comment]
Hi graemeboyd , 
I was just wondering if you were still having issues with this setup? I am guessing you have tried to current mechanism through which you can set custom data as described [here](https://github.com/intercom/intercom-rails#user-custom-data-attributes). I would need more info on how you are currently implementing this via Intercom-Ruby. If you have more examples of what you are trying to do you could reachout to our support team via team@intercom.io. Alternatively, we are trialing a developer forum in the Rails repo via [gitter](https://gitter.im/intercom/intercom-rails). This might be a good place to see if other developers have encountered similar issues. These might be better channels for following up on this rather then GitHub Issues.
