### ISSUE TITLE
Conditionally enable intercom based on controller method or current_company attribute

### ISSUE THREAD

**Issue by jeffblake** [intercom/intercom-rails#160]
Say for example that I only want to track a subset of companies, I should be able to either provide:

- exclude_if: setting for current_company 
- controller method: a simple boolean check such as `!controller.respond_to?(:include_intercom?) || controller.include_intercom?` this would be more flexible, since it could be based off of request parameters, etc

**Comment by choran** [comment]
Hi @jeffblake,
I just wanted to follow up here. Were you able to get something working here with the options you mentioned? Do you not want to register users from these companies either? Just wanted to double check your use case.

**Comment by choran** [comment]
Just closing this for now, please re-open if you are still having issues here
