### ISSUE TITLE
Adjusting the html of intercom widget

### ISSUE THREAD

**Issue by barr-code** [intercom/intercom-rails#161]
For some reason, the Intercom button on my page has the class .intercom-acquire (and associated styling) when I manually include the script provided on my Intercom integration dashboard. However, using the gem to integrate Intercom, that class and styling are missing.

Is there a way to, using config options, specify that the HTML should include that class? Otherwise, how can I have jQuery listen for the Intercom widget to finish loading so that I can add the appropriate classes using JS?

**Comment by RuairiK** [comment]
Hi, you need to tell intercom-rails to include the acquire widget using this config setting:

```ruby
config.include_for_logged_out_users = true
```
Hope this helps.
