### ISSUE TITLE
Can not send `language_override` attribute

### ISSUE THREAD

**Issue by chumakoff** [intercom/intercom-rails#162]
I am trying to send `language_override` attribute like this:  

``` ruby
<%= intercom_script_tag(language_override: I18n.locale.to_s) %>
```

This generates the following script:

``` javascript
<script id="IntercomSettingsScriptTag">
  window.intercomSettings = {"language_override":"ru","app_id":"my_app_id"};
</script>
```

But it does not work. The attribute does not appear in my intercom panel.

**Comment by choran** [comment]
Hi @chumakoff,
Were you seeing any errors here? I just wanted to check if you were still having an issue here. Were you able to get this working with any language override? If you are still having issues with this let me know and any other steps you took to try and resolve it.  Were you able to set this up by hard-coding in the over-ride as described here [here]( https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages)?

**Comment by yunixon** [comment]
same issue, language_override not working
```
//<![CDATA[
window.intercomSettings = {"language_override":"es","app_id":"bfec1qnx","widget":{"activator":".support-link"},"installation_type":"rails"};(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/bfec1qni';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(document.readyState==='complete'){l();}else if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()
//]]>
```

**Comment by whatrocks** [comment]
@choran hello! Long time - not sure if you remember me from our ML blog post days. I was also curious about this issue. Is it possible to send the `language_override` here?
