### ISSUE TITLE
Using intercom_custom_data helper  in models o libs

### ISSUE THREAD

**Issue by nmenag** [intercom/intercom-rails#164]
the use: 

```ruby
def self.generate_custom_data
  intercom_custom_data.user[:registered] = true
end
```

Is possible?, thanks

**Comment by Skaelv** [comment]
Yes it should be possible.
If you are experiencing some issue doing that could you elaborate a little bit more on the steps to reproduce the error by creating a new issue using the 'issue template we provide' ? 
I'm closing this until we get more informations.
