### ISSUE TITLE
api_id on test environment

### ISSUE THREAD

**Issue by jpablobr** [intercom/intercom-rails#176]
After adding the test environment to the list of environments in the Intercom initializer:

```
  # == Enabled Environments
  # Which environments is auto inclusion of the Javascript enabled for
  #
  config.enabled_environments = ['development', 'production', 'test']
```

I thought the widget was going to behave in a similar way as it does in the development environment where the widget will return a dummy `api_id`. But it was until after some debugging when I found out that that's not the case and it isn't obvious since the widget will simply not get rendered at all, since the [`intercom_script_tag.valid?`](https://github.com/intercom/intercom-rails/blob/master/lib/intercom-rails/auto_include_filter.rb#L43) will not be valid. I guess a fix could be to just add the test environment [here](https://github.com/intercom/intercom-rails/blob/master/lib/intercom-rails/script_tag.rb#L127) or update the documentation mentioning that the `IntercomRails.config.app_id` needs to get stubed with something like `allow(IntercomRails.config).to receive(:app_id).and_return('abcd1234')`

## Version info
  - intercom-rails version: 0.2.29
  - Rails version: 4.2.5

## Expected behavior

Test environment to work out of the box or add its setup to the documentation.

## Actual behavior

Difficult to get test environment working.

## Steps to reproduce
 1. Add test environment to the initializer
 2. Run an integration test and notice that the Intercom JS widget isn't there.

## Logs
None.

**Comment by Skaelv** [comment]
Thanks for reporting that. I've added your recommendation to the app_id method. This should be released in gem really soon.

**Comment by antoniosb** [comment]
any update on this?
