### ISSUE TITLE
The README is misleading

### ISSUE THREAD

**Issue by arturoherrero** [intercom/intercom-rails#191]
I've just upgraded to version 0.2.33. After reviewing the README, I was wondering why my app was failing due the error _`intercom_shutdown` is undefined_.

It took me some time to realise that this version doesn't include the code referred in the README.

In order to save time to other users, please:
- Release a new version or update the README with the correct behaviour of the current release.
- Keep a CHANGELOG file.

Thank you!

**Comment by Skaelv** [comment]
Hey,
I've just upgraded to the version 0.2.34. Sorry it took so long and that you had to figure out on your own.
