### ISSUE TITLE
script_tag is being escaped in production

### ISSUE THREAD

**Issue by giovannibonetti** [intercom/intercom-rails#193]
Hi,
this is the problem I am facing, which only occurs in the **production environment**. I think there is an issue with the HTML string being generated.

## Version info
  - intercom-rails version: 0.2.34
  - Rails version: 4.2.6

## Expected behavior
Find the script tag in the HTML like this:
```
<script id="IntercomSettingsScriptTag">
```

## Actual behavior
Found the script tag in the HTML like this:
```
&lt;script id=&quot;IntercomSettingsScriptTag&quot;&gt;
```

## Steps to reproduce
 1. Disable the automatic script generation in the initializer. Place it manually with  `intercom_script_tag`.
 2. Deploy the Rails app (must be set to **production**)
 3. curl myapp.com/page-with-intercom-script | grep intercom

## Workaround
Replace this:
```
<%= intercom_script_tag %>
```

for this - notice the extra "=":
```
<%== intercom_script_tag %>
```

**Comment by choran** [comment]
Hey @giovannibonetti,
Just trying to recreate this ... can you let me know which browser you were testing this on? Or did that make a difference? Wanted to check if this may be browser related.

**Comment by choran** [comment]
Closing this for now but please re-open if you have more questions on this issue

**Comment by giovannibonetti** [comment]
Hi, @choran! I have tested it in Chrome (current version is 52) on Mac OS X 10.11.5

**Comment by rakesh87** [comment]
I can confirm it on Chrom (Version 51.0.2704.106 (64-bit)).
to make it working I did `<%= raw intercom_script_tag %> `

**Comment by kyteague** [comment]
Also getting this issue.
