### ISSUE TITLE
Intercom not working on localhost for logged-in users

### ISSUE THREAD

**Issue by abrambailey** [intercom/intercom-rails#195]
I am not seeing the messenger icon appear and also see the following errors:
```
intercom.ce2651f4.js:7 POST https://api-ping.intercom.io/vjs/users/ping 403 (Forbidden)send @
intercom.ce2651f4.js:7le.extend.ajax @ 
intercom.ce2651f4.js:7e.exports @
 intercom.ce2651f4.js:15m.post @
 intercom.ce2651f4.js:15o.extend._post @
 intercom.ce2651f4.js:15o.extend.createOrUpdateUser @ 
intercom.ce2651f4.js:15i.createOrUpdateUser @ 
intercom.ce2651f4.js:15i.throttledCreateOrUpdateUser @ 
intercom.ce2651f4.js:15c.extend.createOrUpdateUser @
 intercom.ce2651f4.js:8c.extend.initialize @ 
intercom.ce2651f4.js:8(anonymous function) @ 
intercom.ce2651f4.js:4t @ 
intercom.ce2651f4.js:1i @ 
intercom.ce2651f4.js:4(anonymous function) @ 
intercom.ce2651f4.js:4t @ 
intercom.ce2651f4.js:1(anonymous function) @
 intercom.ce2651f4.js:1t @ 
intercom.ce2651f4.js:1(anonymous function) @ 
intercom.ce2651f4.js:1(anonymous function) @ 
intercom.ce2651f4.js:1
```

The messenger icon is appearing for visitors only.

Seems the issue is here:

```javascript
rn && le.ajaxTransport(function(e) {
    if (!e.crossDomain || se.cors) {
        var t;
        return {
            send: function(n, i) {
                var o, r = e.xhr(), a = ++nn;
                if (r.open(e.type, e.url, e.async, e.username, e.password),
                e.xhrFields)
                    for (o in e.xhrFields)
                        r[o] = e.xhrFields[o];
                e.mimeType && r.overrideMimeType && r.overrideMimeType(e.mimeType),
                e.crossDomain || n["X-Requested-With"] || (n["X-Requested-With"] = "XMLHttpRequest");
                for (o in n)
                    void 0 !== n[o] && r.setRequestHeader(o, n[o] + "");
                >>>>>>>>>>>>>> r.send(e.hasContent && e.data || null ), <<<<<<<<<<<<<<<<
                t = function(n, o) {
                    var s, c, l;
                    if (t && (o || 4 === r.readyState))
                        if (delete on[a],
                        t = void 0,
                        r.onreadystatechange = le.noop,
                        o)
                            4 !== r.readyState && r.abort();
                        else {
                            l = {},
                            s = r.status,
                            "string" == typeof r.responseText && (l.text = r.responseText);
                            try {
                                c = r.statusText
                            } catch (m) {
                                c = ""
                            }
                            s || !e.isLocal || e.crossDomain ? 1223 === s && (s = 204) : s = l.text ? 200 : 404
                        }
                    l && i(s, c, l, r.getAllResponseHeaders())
                }
                ,
                e.async ? 4 === r.readyState ? setTimeout(t) : r.onreadystatechange = on[a] = t : t()
            },
            abort: function() {
                t && t(void 0, !0)
            }
        }
    }
})
```

**Comment by abrambailey** [comment]
Weird. Just stopped working in production with the same message for logged in users.

**Comment by abrambailey** [comment]
Specifying an API key via `config.api_key` in the initializer made intercom crash in production ... after removing it that line, intercom is working again in production. Still not sure why its failing on localhost.

**Comment by Skaelv** [comment]
Hey. If you whitelisted some domain in the platform settings, the widget won't show up on localhost and on every other website.
To add some domains to the whitelisted apps you can just go in `App Settings > Intercom Messenger` section and add `localhost:3000` in your whitelisted domains while you are testing Intercom locally.

![image](https://cloud.githubusercontent.com/assets/5072452/15246724/f4de16b4-1906-11e6-9db7-7463c7e8ea9e.png)

It would be wise to delete it after as everybody using `localhost:3000` will be able to load your intercom widget on their dev env. You can also use ngrok to prevent from this problem.

**Comment by abrambailey** [comment]
Hey @Skaelv I haven't actually set any whitelisted domains. Also, as I mentioned intercom messenger is loading for logged out visitors just fine on localhost.. just not working for logged in users.

**Comment by abrambailey** [comment]
By the way, I just tried testing intercom on `qa.hearingtracker.com` and it isn't working there either.. seeing `intercom.05deceb0.js:7 POST https://api-ping.intercom.io/vjs/users/ping 403 (Forbidden)` I even tried adding `qa.hearingtracker.com` to my whitelist, but still getting the error.

**Comment by Skaelv** [comment]
The only reason I can think of then is that you enabled [secure mode](https://docs.intercom.io/configure-intercom-for-your-product-or-site/staying-secure/enable-secure-mode-on-your-web-product) in Intercom and you are not providing a user_hash in the widget.

**Comment by abrambailey** [comment]
Why would it be working in production, but not qa or localhost?

**Comment by abrambailey** [comment]
By the way, I turned off secure mode and still not working with logged in users... only for qa and localhost.

**Comment by Skaelv** [comment]
You can't turn off secure mode once it's enabled. So that might me the reason of your problem here.

**Comment by abrambailey** [comment]
Oh NM, I only commented out the api_secret in my init file.. so I guess that has no effect.. It's uncommented now.. So you are saying secure mode doesn't work for logged in users from other domains, even when they're on the whitelist?

**Comment by abrambailey** [comment]
Is there a way we can chat?

**Comment by choran** [comment]
Hi @abrambailey,
Secure mode will cause issues if it is enabled and you have not set up the api_secret in that rails setting. You can see more info about secure more [here](https://docs.intercom.io/configure-intercom-for-your-product-or-site/staying-secure/enable-secure-mode-on-your-web-product) which may help clarify some of the issues you were seeing? Were you able to resolve this or are your still unable to see the widget for logged in users?

**Comment by choran** [comment]
Closing this for now, please re-open if you are still experiencing any issues

**Comment by fikriauliya** [comment]
I also encounter this: the widget disappear when logged in.
My app is SPA with React. I didn't (and haven't) set up secure mode

**Comment by sakshikakkar** [comment]
I have the same problem. I have set api_secret and include_for_logged_out_users = true. The rest of the intercom configurations are as default. I am not sending any custom data. The email and id with which the user logs in becomes available in the messages received. But the widget disappears for the user.

**Comment by sakshi1212** [comment]
found this 

> Note that even after you’ve installed the code for logged-in users, the Intercom Messenger won’t appear for them until you’ve started a trial of Intercom Engage or Resolve.

here : https://app.intercom.io/a/apps/lea56gnc/guide/web_integration/web_integration_users#

I started a trial of Engage, and now it works fine even for logged in users.
