### ISSUE TITLE
Import task does not clear the `companies` of an User.

### ISSUE THREAD

**Issue by lucasmazza** [intercom/intercom-rails#199]
## Version info
  - intercom-rails version: `0.2.34`
  - Rails version: `5.0.0.rc1`

## Expected behavior

When a user on my system is removed from all its companies associations, it's matching profile on Intercom still belongs to the last company that was associated with the user.

## Actual behavior

The import task doesn't clear the `companies` list on Intercom due a `companies.present?` guard at https://github.com/intercom/intercom-rails/blob/34b1baab23d75170aa305c37976219fe8efd82ab/lib/intercom-rails/import.rb#L105. 

If this guard is no longer relevant I can send a PR removing it.

**Comment by eugeneius** [comment]
I think the guard exists to avoid calling `map` on `nil` in [this case](https://github.com/intercom/intercom-rails/blob/34b1baab23d75170aa305c37976219fe8efd82ab/lib/intercom-rails/proxy/company.rb#L15) or [this case](https://github.com/intercom/intercom-rails/blob/34b1baab23d75170aa305c37976219fe8efd82ab/lib/intercom-rails/proxy/company.rb#L17), so we can't just remove it. We could change it to `unless companies.nil?` though.

**Comment by lucasmazza** [comment]
@eugeneius makes sense - do you want me to get a PR ready with the patch?

**Comment by eugeneius** [comment]
If you want to, that would be great! 👌

**Comment by lucasmazza** [comment]
@eugeneius I've deployed the latest version and looks like the fix wasn't enough to help on our use case - the users aren't being updated as expected. I talked with Marshall through the in app chat on Intercom and he mentioned about possibly this being a server side issue on the Intercom API.
