### ISSUE TITLE
Intercom script get inserted in a wrong place

### ISSUE THREAD

**Issue by MaximAbramchuck** [intercom/intercom-rails#201]
## Version info
  - intercom-rails version: 0.2.31
  - Rails version: 5.0.0.rc1

## Expected behavior

I've used a widget like a cities map from Intercom, which I've inserted to my html page.

It looked something like that:

`<iframe id="intercom_map_iframe" src="" frameborder="0" height="600" width="800"></iframe><script>(function(){var d = document.getElementById('intercom_map_iframe').contentWindow.document;d.open().write('<body onload="document.location.replace(\'https://share.intercom.io/_______?embed=true\')"></body>');d.close();})();</script>`

## Actual behavior

It did not appear on the page.

I've spent some time trying to fix this issue, looked through and there is what I got:

In this code here

https://github.com/intercom/intercom-rails/blob/master/lib/intercom-rails/auto_include_filter.rb#L34

```ruby
def include_javascript!
  response.body = response.body.gsub(CLOSING_BODY_TAG, intercom_script_tag.to_s + '\\0')
end
```

It finds any `<\/body>` symbols on the page and inserts intercom script there. So, after that script for adding map has these symbols it tried to insert script tag there which was breaking the html markup.

**Comment by kimroen** [comment]
One suggested fix could be to make sure we only match the last occurrence of the closing body tag, with something like this:

```diff
-CLOSING_BODY_TAG = %r{</body>}
+CLOSING_BODY_TAG = %r{.*</body>}
```

(I don't this would work with the way `gsub` is used, but hopefully the idea is clear enough)

Or we could use something like nokogiri to parse the document and add it before the end of the outmost body tag way, but maybe performance would be a concern.

**Comment by choran** [comment]
Hi, 
For cases such as this, or situations where there is no closing body tag we do allow for manually inserting the Intercom Javascript. We describe this in the  trouble shooting sections [here](https://github.com/intercom/intercom-rails#manually-inserting-the-intercom-javascript). That might be a better workaround then trying to capture the different body locations? Were you able to get a workaround here or did you try manually inserting the javascript?
