### ISSUE TITLE
Import Rake Task no longer works

### ISSUE THREAD

**Issue by ehoch** [intercom/intercom-rails#202]
Rake task no longer works since old API was deprecated. Should be updated or removed from gem.

**Comment by Skaelv** [comment]
The import task was using a deprecated version of the API. We have no plan to replace it right now.
You can do this using the `intercom-ruby` gem.

**Comment by martinpeck** [comment]
@Skaelv Do you have an example of how this might be done? The old rake task made it easy to batch up a number of updates. Is this something that the `intercom-ruby` gem natively handles for us, or do we have to roll our own batching of updates?

**Comment by thomasgallagher** [comment]
I don't consider this ticket closed.

We used this function quite a lot when adding new fields as it was a quick and easy way of synchronising historical records.

Deprecating it without a replacement is not very helpful and has made my working day that much longer.

I would appreciate an example of how to do the intercom:import task in intercom-ruby. I can probably work it out myself but would rather spend time working on features for our own app.

Many thanks in advance, Tom

**Comment by thomasgallagher** [comment]
Any news on this guys? It's been a month and our DB is growing increasingly out of sync.

**Comment by thomasgallagher** [comment]
For anyone looking for this I thought I'd share my solution for our product.

The job errors whine about the header type not being json (intercom-ruby should be setting this?) but it seems to update regardless.

Sleep is arbitrary to ensure we don't blow out the throttle.

```
class IntercomImporter
  def self.import_all_users
    intercom = Intercom::Client.new app_id: 'YOUR_APP_ID', api_key: 'YOUR_KEY'
    user = User.find_in_batches(batch_size: 100) do |users|
      users_to_update = []

      for user in users
        user_attrs = {
          user_id: user.id,
          email: user.email,
          created_at: user.created_at,
          name: user.name,
          custom_attributes: {
            business_count: user.businesses_count,
          }
        }
        users_to_update << user_attrs
      end

      result = intercom.users.submit_bulk_job create_items: users_to_update
      puts "Result: #{result.to_yaml}"

      sleep 2
    end
  end
end
```

**Comment by casare** [comment]
Thanks, @thomasgallagher!
What a shame on Intercom, to remove an often used feature and even don`t reply questions about this move!!

**Comment by casare** [comment]
As I`m using ruby 2.0 and  could not install intercom-ruby, 
here is a version using intercon rest api directly...

    class IntercomImporter

        URL = "https://api.intercom.io/bulk/users"
        BATCH_SIZE = 100 # Limit defined by Intercom

        def self.import_all_users
            new.import_all_users
        end

        def import_all_users
            User.find_in_batches(batch_size: BATCH_SIZE) do |users|
                ret = Util.post_json(
                    URL, 
                    {items: users.map{|u| user_atts u}}, 
                    basic_auth
                )
                Rails.logger.info "IntercomImporter ret: #{ ret }"
                sleep 2
            end
        end

        def user_atts user
            atts = {user_id: user.id}
            intercom_fields.each_pair do |field_name, value_getter|
                atts[field_name] = if value_getter.is_a?(Proc)
                    value_getter.call user
                else
                    user.send value_getter
                end
            end
            atts
        end

        def intercom_fields
            @fields ||= IntercomRails.config.user.custom_data
        end

        def basic_auth
            [
                ENV['INTERCOM_APP_ID'], 
                ENV['INTERCOM_APP_KEY']
            ]
        end

        def post_json url, body, basic_auth = nil
            uri = URI.parse url

            header = {
                'Content-Type' => 'application/json',
                'Accept'       => 'application/json'
            }
            
            req = Net::HTTP::Post.new uri.request_uri, header
            req.basic_auth *basic_auth if basic_auth
            req.body = body.to_json

            resp = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == 'https') do |http|
                http.request req
            end

            [resp.code.to_i, JSON.parse(resp.body)]
        end

    end

**Comment by Hungor** [comment]
@casare +1 !!

It is not very nice to deprecate such an useful function. I have not received any messages from the Intercom team regarding the new access token method either.

**Comment by jeremyhaile** [comment]
I'm also frustrated at the removal of this with a) no replacement and b) not even giving us an example of how to replicate this.
