### ISSUE TITLE
Do not auto include Intercom when status is a 404

### ISSUE THREAD

**Issue by mikeycgto** [intercom/intercom-rails#211]
What's the best way to accomplish this?

Basically, we don't want intercom to get injected if the response is a 404 (since it's being injected on our 404 error page currently).

**Comment by choran** [comment]
Hi @mikeycgto 
We dont have a built in feature for this but we do provide an example of how to do something similar with for use cases such as specific users ... i.e. you only want the include Intercom for certain users. You can see that [here](https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customizing-the-intercom-messenger). 

So if you know your error page then you could check for it here and not load Intercom when this page is accessed.

Alternatively, I think you could use the CSS display property to hide the element on a particular error page:
  #intercom-frame, 
        #intercom-container {
            display:none;}

But all of this would depend on how you handle the 404 in your workflow?

**Comment by mikeycgto** [comment]
We added the following to the `ApplicationController` class and it achieved what we wanted:

```ruby
def intercom_rails_auto_include
  super unless response.status >= 400
end
```
