### ISSUE TITLE
Link to app ID in docs appears to be broken

### ISSUE THREAD

**Issue by rossettistone** [intercom/intercom-rails#214]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-rails version: N/A
  - Rails version: N/A

## Expected behavior
Clicked on link to Intercom app ID (https://app.intercom.io/apps/api_keys) in the GitHub readme docs. Expected to reach a page that contained the ID or instructions to get it.

## Actual behavior
Was redirected to sign-in. After sign-in, was redirected to the Intercom logged-in dashboard with a flash message indicating that the requested page (with app ID) was not found.

## Steps to reproduce
 (see above)

## Logs
N/A

**Comment by choran** [comment]
cool, should be fixed now. let me know if you have any issues
