### ISSUE TITLE
New messenger disregards config.inbox.style = :custom option

### ISSUE THREAD

**Issue by snkashis** [intercom/intercom-rails#218]
Upgraded to the new messenger this week, and our old configuration option which only triggered messenger visibility on specific anchor clicks is now being bypassed - the messenger automatically appears on every page.

**Comment by mmartinic** [comment]
Hi @snkashis, we added a new config option `Config.hide_default_launcher`. Setting that to `true` will hide the default messenger launcher.
This will be available in next version of `intercom-rails` gem.
