### ISSUE TITLE
After action callback :intercom_rails_auto_include has not been defined

### ISSUE THREAD

**Issue by attenzione** [intercom/intercom-rails#235]
I'm using this method to disable intercom for some controller, but for staging environment i completely disabled it in config. Seems this issue not related to disabling it for specific environment, as I investigated source code, this method should exist anyway. I think it's Rails 5
With Rails 4 there is no issue.
## Version info
- intercom-rails version: 0.3.2
- Rails version: 5.0.0.1
## Logs

After process_action callback :intercom_rails_auto_include has not been defined (ArgumentError)

**Comment by nburns** [comment]
Also having this same problem, any word on a fix?

**Comment by attenzione** [comment]
add ```raise: false``` to ```skip_after_action```

**Comment by nburns** [comment]
Setting `config.enable_dependency_loading = true` in config/application.rb fixed the issue for me. 
http://blog.bigbinary.com/2016/08/29/rails-5-disables-autoloading-after-booting-the-app-in-production.html

**Comment by Skaelv** [comment]
Seems to be related to rails 5 disabling autoloading in production as mentioned by @nburns. I'll close this one as I don't think there is much we can do in `intercom-rails` gem. Let us know if you still have this issue.
