### ISSUE TITLE
Bug - User creation duplicates

### ISSUE THREAD

**Issue by alaouy** [intercom/intercom-rails#238]
Lately I noticed that there were duplicates being created of my users accounts on intercom, 
I have three models (Doctor,User,Assistant) each one of them with devises attributes, and I sync them on intercom with some other custom attributes, here is my config file

 ```ruby
config.user.current = Proc.new { current_user || current_doctor || current_assistant }
config.user.model = Proc.new { Doctor }
```
I'm using MongoDB and I use the _id field on each model to set the user_id attribute on intercom, and another attribute `account_type` with values ('doctor', 'user', 'assistant') to differentiate between them on intercom.
I noticed this bug when some of our new users automated emails fired for old existing users, and found that the new ones were attributed with a different user_id. Here is an example:

<img width="1367" alt="capture_d ecran_2016-11-01_a_14_24_12" src="https://cloud.githubusercontent.com/assets/3118889/19892952/395ddb20-a03f-11e6-9ace-aac617482304.png">

Is there a fix for this ? Or am I doing something wrong ?

## Version info
  - intercom-rails version: 0.2.29
  - Rails version: 4.2.5

**Comment by brainnzzz** [comment]
> Note that the following lookup order applies when updating users - id then user_id then email, and results in the following logic -
-    id is matched - the user_id and email will be updated if they are sent.
-     user_id match - the email will be updated, the id is not updated.
-     email match where no user_id set on the matching user - the user_id will be set to the value sent in the request, the id is not updated.
-     email match where is a user_id on the matching user - a new unique record with new id will be created if a new value for user_id is sent in the request.


link - https://developers.intercom.com/reference#create-or-update-user

**Comment by alaouy** [comment]
@brainnzzz Thanks for you reply, I've found the problem that caused the duplicates bug, it was caused by the model in my configuration, I had 3 models and I used only one which caused multiple account to be synced by error, the fix was to reset all user accounts and update the configuration model to this :
```ruby
config.user.current = Proc.new { current_user || current_doctor || current_assistant }
config.user.model   = Proc.new { (current_user || current_doctor || current_assistant).class }
```
