### ISSUE TITLE
API Keys are being deprecated

### ISSUE THREAD

**Issue by seb-sykio** [intercom/intercom-rails#258]
hi,

is it possible to use an access token?

thanks

**Comment by Skaelv** [comment]
Access token are intended for your own personal use. If you want to request your own data.
Do not share access token with 3rd party integrations! Third party integrations can use OAuth which is way safer to share credentials and assure you the application has been validated by Intercom.
More informations  in [official docs](https://developers.intercom.com/reference#personal-access-tokens-1)
