### ISSUE TITLE
Token support?

### ISSUE THREAD

**Issue by justinperkins** [intercom/intercom-rails#281]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-rails version: 0.3.4
  - Rails version: 5.0.0.1

## Expected behavior
  - README for latest version (0.3.8 at time of writing) would explain how to update our intializer 

## Actual behavior
  - README still mentions using an API key and secret

## Steps to reproduce
 1. Look at your API Keys page in Intercom
 2. Note that it says API Keys are being deprecated
 3. Look at latest version of README in intercom-rails, instructions say to use API keys

**Comment by henrypoydar** [comment]
👍

**Comment by scottsouthard** [comment]
The Rails library actually doesn't require an API Key at the moment, rather it just needs your app's App ID (and the Identity Verification secret key if you're using Identity Verification). There isn't any need to include an API Key _or_ an Access Token. 👍
