### ISSUE TITLE
Do i need to change from api key to access token?

### ISSUE THREAD

**Issue by kurianic** [intercom/intercom-rails#282]
I am a beginner in Ruby on Rails please help me to integrate access token method in my intercom-rails. I don't know the exact version of intercom-rails that I am using but I found this one
This was the line in my git lock file.
intercom-rails (0.2.24).

**Comment by scottsouthard** [comment]
Nope! The Rails library actually doesn't require an API Key at the moment, rather it just needs your app's App ID (and the Identity Verification secret key if you're using Identity Verification). There isn't any need to include an API Key or an Access Token. 👍

https://github.com/intercom/intercom-rails/issues/281

**Comment by kurianic** [comment]
@scottsouthard  thank you for your valuable help. I got an email from intercom it says API keys are deprecating from April 8th. Are you sure about my chat system will work without any issues from then? Thanks in advance

**Comment by scottsouthard** [comment]
@kurianic sure thing! The Intercom integration with your Rails app will continue to work here, and you won't need to change anything as far as API Keys or Access Tokens go. If you are using the Ruby Library or any other REST API functionality, you would need to make that change, but the built-functionality of the Rails library doesn't require an API Key or Access Token, so you won't need to change anything. 

Feel free to write into the support team at team@intercom.io if you have any questions on things.
