### ISSUE TITLE
Removing intercom

### ISSUE THREAD

**Issue by rishijain** [intercom/intercom-rails#309]
I have configured intercom using this gem. But later I wanted to remove it. I had removed the intercom.rb file, removed the gem from the Gemfile.

Restarted the app server.

## Version info
  - intercom-rails version: 0.4.0
  - Rails version: 4.2.9

## Expected behavior
Should not add intercom js file

## Actual behavior
JS file still loads in the html pages

## Steps to reproduce
 1. Add intercom-rails gem
 2. configure the intercom.rb file
 3. bundle install
 4. restart the server
 5. check if js file is added
 6. now stop the server
 7. remove the intercom.rb file, remove the gem from Gemfile
 8. bundle install, start the server.
 9. check the html which is loaded.

**Comment by eoin** [comment]
@rishijain I've following your steps with a fresh install and can't seem to reproduce the issue. On restart, Intercom is no longer included. Feel free to reopen if this is still an issue, and thanks for taking the time to report it.
