### ISSUE TITLE
Messenger is not visible in Rails 6.0rc2

### ISSUE THREAD

**Issue by brenogazzola** [intercom/intercom-rails#312]
This gem was working fine with 6.0rc1, but I just updated my app to 6.0rc2 and noticed that Messenger is no longer visible.

## Version info
  - intercom-rails version: 0.40
  - Rails version: 6.0rc2

## Expected behavior
Messenger should be visible;

## Actual behavior
Messenger is not visible;

## Steps to reproduce
 1. Install Rails 6.0rc1 and intercom-rails. Validate that Messenger is visible
 2. Upgrade to Rails 6.0rc2. Messenger no longer visible

**Comment by nymerias** [comment]
Hi @brenogazzola, I've tried to reproduce this but the Messenger is appearing in my test app even when upgrading to `rails 6.0.0.rc2`. Would you happen to have a sample we could take a look at?

**Comment by brenogazzola** [comment]
Hey @nymerias. This is strange. I'm literally only changing the Rails version in my Gemfile from 6.0rc1 to 6.0rc2 and doing a `bundle` for it to stop working. I'll check if I have anything else in my project's config that might be part of the cause.

**Comment by brenogazzola** [comment]
@nymerias sample is in the link below. I created a new app with a `User` model, a single `show` view that can be accessed from `localhost:3000`, as well as the `seed` needed to create the first user.

Them I followed the instructions in the README to add intercom (I removed my app-id from the repo, you will have to add it).

In rc1 I see the messenger, in rc2 I don't.

https://github.com/brenogazzola/intercom-demo-app

**Comment by nymerias** [comment]
Thanks for that @brenogazzola, I was able to reproduce. This is strange! I will investigate this week.

**Comment by eugeneius** [comment]
Hey @brenogazzola, [v0.4.1](https://github.com/intercom/intercom-rails/releases/tag/v0.4.1) was just released with a fix for this issue. Thanks again for writing up really clear steps to reproduce the problem! 🙌

**Comment by brenogazzola** [comment]
Glad to help, and thanks for fixing the issue!
