### ISSUE TITLE
Intercom preventing some users from signing in or signing up

### ISSUE THREAD

**Issue by summera** [intercom/intercom-rails#316]
## Version info
  - intercom-rails version: `0.3.5`
  - Rails version: `5.2.3`

## Expected behavior
Intercom remote scripts should load quickly and successfully and not interfere with sign in/sign up forms.

## Actual behavior
Some users on our site are unable to sign in or sign up using Chrome due to some issue with loading intercom JS remote scripts. We've had several cases of this. It's happened with Chrome `76.0.3809.100`, but it could be other versions as well. Unfortunately I can't reproduce myself. To make sure it was Intercom, we've had users who were experiencing this issue temporarily block everything **but** Intercom using an Ad Blocker. Once they did this, they were able to sign in/sign up successfully.

The users are seeing *Waiting for js.intercomcdn.com...* or *Waiting for api-iam.intercom.io...* in the bottom left of their browser. It seems to be stuck waiting for these scripts for some reason.

![63624681-19403680-c5b2-11e9-82c6-ba89da296f43](https://user-images.githubusercontent.com/2474416/63783636-95849380-c8aa-11e9-838d-f04d9f0a4c0f.png)

When the click the form submit button, nothing happens and the message saying that it is loading Intercom remains.

## Steps to reproduce
As mentioned, I can't reproduce myself but we have had many reports of this issue starting about 2 weeks ago.

**Comment by summera** [comment]
Looks like this was resolved at some point as we haven't had any recent reports.

**Comment by Kenner-G** [comment]
experiencing this :/, our website is stalling
