### ISSUE TITLE
api_base config key unsupported

### ISSUE THREAD

**Issue by johanbaaij** [intercom/intercom-rails#328]
## Version info
  - intercom-rails version: 1.1.7
  - Rails version: 4.2.10

Was adviced to add `api_base` to our configuration to deal with Vietnam ISP issues. Are there any other ways to pass the api_base parameter with Rails?

## Logs
`NoMethodError: undefined method api_base= for IntercomRails::Config:Class`

**Comment by lloydliyu** [comment]
Hey @johanbaaij 

I just merged a change here: https://github.com/intercom/intercom-rails/pull/329

The version of intercom-rails hasn't been bumped yet so you might have to try and target the master branch in your gemfile as per this article from bundler https://bundler.io/guides/git.html

If that is something you can do, let me know if all works as expected.

I'll also loop back here when the version is bumped.

**Comment by lloydliyu** [comment]
This should now be fixed in version 0.4.2
