### ISSUE TITLE
Error: invalid filter name app_id

### ISSUE THREAD

**Issue by rassom** [intercom/intercom-rails#338]
I'm using Rails's built-in CSP, so cannot use the instructions provided for the Twitter Secure Headers gem (https://github.com/intercom/intercom-rails#automatic-insertion).

When using the manual insertion method instead (https://github.com/intercom/intercom-rails#manual-insertion) to make Intercom work with CSP - content security policy - , I get the error: 
intercom rails invalid filter name app_id

Any ideas why the `intercom rails invalid filter name app_id`error is happening?

## Version info
  - intercom-rails version: 0.4.2
  - Rails version: 5.2.4.4

**Comment by rassom** [comment]
@arindambarman-intercom Any chance you could take a look at this? Thanks 🙏

**Comment by arindambarman-intercom** [comment]
Hey @rassom sorry missed this earlier. Can you share your integration script? From the error message itself it looks like it is unrelated to CSP. Also can paste the stacktrace?

**Comment by rassom** [comment]
Hey @arindambarman-intercom 

Agree that it looks unrelated to CSP, so I dug a bit deeper and found out that the invalid filter error actually came from HAML. 

Renaming my Intercom partial from _intercom.html.haml to _intercom.html.erb solved the filter error. 

But ... it still doesn't work as I now get this error:
````
undefined method `intercom_script_tag' for #<#<Class:0x00007fef3dc17148>:0x00007fef3d5e8178>
   1  - unless session[:impersonating]
[0m   2    <div id="Intercom">
[0m❯  3  [1;3m    <%= intercom_script_tag({
[0m   9      }, {
````

Here's the integration script:
````
  <div id="Intercom">
    <%= intercom_script_tag({
      :app_id => 'some-app-id',
      :user_id => current_user.id,
      :email => current_user.email,
      :name => current_user.first_name + " " + current_user.last_name,
      :created_at => current_user.created_at
    }, {
      :secret => 'some-secret-key',
      :widget => {:activator => '#Intercom'},
      :nonce => Current.content_security_policy_nonce
    }) %>
 </div>
````

I checked that the gem is installed properly and it is. 

Any ideas why I get the undefined method error?

**Comment by rassom** [comment]
Hey @arindambarman-intercom,

Thanks for replying.

Found out that the error was caused by (invalid) HAML syntax. 

Invalid syntax:
````
- if logged_in?
  = intercom_script_tag({                         
      :app_id => 'your-app-id',                   
      :user_id => current_user.id,               
      :email => current_user.email,              
      :name => current_user.name,                 
      :created_at => current_user.created_at      
    }, {                                          
      :secret => 'your-apps-api-secret',          
      :widget => {:activator => '#Intercom'},     
      :nonce => get_nonce_from_your_csp_framework 
    })        
````

Valid syntax:
````
- if logged_in?
  = intercom_script_tag({                                                 |
      :app_id => 'your-app-id',                                           |
      :user_id => current_user.id,                                      |
      :email => current_user.email,                                    |
      :name => current_user.name,                                   |
      :created_at => current_user.created_at                  |
    }, {                                                                                  |
      :secret => 'your-apps-api-secret',                           |
      :widget => {:activator => '#Intercom'},                    |
      :nonce => get_nonce_from_your_csp_framework |
    })                                                                                     |
````

So all good and working now.

Sorry for the inconvenience and have a great weekend.

Best wishes,
Rasmus
