### ISSUE TITLE
The Intercom launcher is not loading with Turbo

### ISSUE THREAD

**Issue by arutinn** [intercom/intercom-rails#351]
## Version info
  - intercom-rails version: 0.4.2
  - Rails version: 7.1.3.2

## Expected behavior
Loading intercom launcher.

## Actual behavior
The intercom launcher is not loading when an application uses turbo to load pages (because turbo has different event names).

## Steps to reproduce
 1. Setup Rails project with Turbo and Intercom
 2.  Visit the page without Intercom launcher then go to page with Intercom launcher using the turbo
 3. The intercom launcher is missing (not loaded)

**Comment by eugeneius** [comment]
Hi @arutinn, thanks for the report - 1.0.1 was just released with a fix for this issue.
