### ISSUE TITLE
Add an option in the config file to exclude certain types of users

### ISSUE THREAD

**Issue by risinglf** [intercom/intercom-rails#77]
Is it possible to exclude some types of users from being imported to Intercom.io?

The first simple solution I found was to skip the controller filter, but when I ran the import rake task all of my users are imported into Intercom.io.

I think an useful feature would be having an option in the config file to include/exclude certain types of users, with a Proc.

**Comment by benoittgt** [comment]
Hello

Thanks for this thread. I'm using https://github.com/rcook/user_impersonate2 to connect to the platform as customer. I would love to disable intercom when I'm using impersonate. I've tried to set `  config.user.exclude_if = Proc.new { current_staff_user }` but it doesn't work. @eoin any idea?

**Comment by benoittgt** [comment]
The answer is here : https://github.com/intercom/intercom-rails/issues/103
