### ISSUE TITLE
With activeadmin

### ISSUE THREAD

**Issue by Paxa** [intercom/intercom-rails#79]
How to disable intercom button on some pages? For example in activeadmin

**Comment by Superpencil** [comment]
@lucasfais

**Comment by robert-resemble** [comment]
Leaving this here for a future reader, it seems like Intercom, by default, injects itself into all pages via `auto_include`. For some reason this conflicts with rails engines like `ActiveAdmin` (I think it's an engine) and `RailsAdmin` (definitely an engine). The solution is as Paxa mentions above: disable the auto inclusion action in your Admin controller. For Rails admin, you can create a parent controller (see Rails admin docs) and run `skip_before_action :intercom_rails_auto_inclusion`
