### ISSUE TITLE
Custom activator doesn't work with new messaging box update.

### ISSUE THREAD

**Issue by vipulnsward** [intercom/intercom-rails#87]
Previously, this

``` ruby
= intercom_script_tag nil, widget: { activator: '.intercom' }
```

used to work, without any changes from intercom website, and overrode any custom settings done to make the class `.intercom` act as activator and also not show the intercom messaging icon.

With the new messaging App, the icon still shows even after having a custom  activator, unless disabling from here http://take.ms/x29NX

**Comment by ijunaidfarooq** [comment]
for now, we are just adding `config.inbox.style = :custom` and putting id="Intercom" but nothing happened
